
'$INCLUDEONCE

' Type system flags (declarations only)
DIM SHARED ISSTRING AS LONG
DIM SHARED ISFLOAT AS LONG
DIM SHARED ISUNSIGNED AS LONG
DIM SHARED ISPOINTER AS LONG
DIM SHARED ISFIXEDLENGTH AS LONG
DIM SHARED ISINCONVENTIONALMEMORY AS LONG
DIM SHARED ISOFFSETINBITS AS LONG
DIM SHARED ISARRAY AS LONG
DIM SHARED ISREFERENCE AS LONG
DIM SHARED ISUDT AS LONG
DIM SHARED ISOFFSET AS LONG

' Type constants (declarations only)
DIM SHARED STRINGTYPE AS LONG
DIM SHARED BITTYPE AS LONG
DIM SHARED UBITTYPE AS LONG
DIM SHARED BYTETYPE AS LONG
DIM SHARED UBYTETYPE AS LONG
DIM SHARED INTEGERTYPE AS LONG
DIM SHARED UINTEGERTYPE AS LONG
DIM SHARED LONGTYPE AS LONG
DIM SHARED ULONGTYPE AS LONG
DIM SHARED INTEGER64TYPE AS LONG
DIM SHARED UINTEGER64TYPE AS LONG
DIM SHARED SINGLETYPE AS LONG
DIM SHARED DOUBLETYPE AS LONG
DIM SHARED FLOATTYPE AS LONG
DIM SHARED OFFSETTYPE AS LONG
DIM SHARED UOFFSETTYPE AS LONG
DIM SHARED UDTTYPE AS LONG

' UDT arrays (declarations only - will be REDIM'd in type_init.bas)
DIM SHARED udtxname() AS STRING * 256
DIM SHARED udtxcname() AS STRING * 256
DIM SHARED udtxsize() AS LONG
DIM SHARED udtxnext() AS LONG
DIM SHARED udtxvariable() AS INTEGER
'elements
DIM SHARED udtename() AS STRING * 256
DIM SHARED udtecname() AS STRING * 256
DIM SHARED udtesize() AS LONG
DIM SHARED udtetype() AS LONG
DIM SHARED udtetypesize() AS LONG
DIM SHARED udtearrayelements() AS LONG
DIM SHARED udtenext() AS LONG

